---
# task file for wildfly
- name: Download WAR to server
  command: curl -O https://raw.githubusercontent.com/aeimer/java-example-helloworld-war/master/dist/helloworld.war '{{ path_war }}'
  register: ware_name

- name: backup war
  shell: "cp {{ path_war }}/{{ war_name }} {{ path_deploy }}/{{ ware_name }}"
 

