---
# Tareas de instalacion de Wildfly
#- name: Descarga de Archivos
#  include_tasks: descarga.yml

#- name: Instalacion del ware
#  include_tasks: instalacion.yml
<<<<<<< HEAD
=======
 
- name: DESInstalacion del ware
  include_tasks: desinstalacion.yml
>>>>>>> 08a85bbea5cc5e35e19641211eef4c1fd02c7283

- name: DesInstalacion del ware
  include_tasks: desinstalacion.yml
